---
# Copyright 2015 FUJITSU LIMITED

- name: Install OpenJDK
  apt: name=openjdk-7-jre-headless state=present
  when: ansible_os_family == "Debian"

- name: Install OpenJDK
  yum: name=java-1.7.0-openjdk state=present
  when: ansible_os_family == "RedHat"

- include: elasticsearch.yaml tags=elasticsearch
- include: kibana.yaml tags=kibana
- include: logstash.yaml tags=logstash
- include: monasca-log-transformer.yaml tags=monasca-log-transformer
- include: monasca-log-persister.yaml tags=monasca-log-persister
