---
# ©Copyright 2015 Hewlett-Packard Development Company, L.P.

dependencies:
  - python-dev
  - build-essential
  - python-mysqldb
  - libmysqlclient-dev
notification_log_dir: "{{ monasca_log_dir }}/notification"
notification_systemd_service: /etc/systemd/system/monasca-notification.service
notification_upstart_conf: /etc/init/monasca-notification.conf
notification_user: mon-notification
monasca_group: monasca
